var transitionRay = [
    //Basic compounds
    { name: "Rust", formula: "Fe₂O₃·nH₂O" },
    { name: "Glucose", formula: "C₆H₁₂O₆" },
    { name: "Water", formula: "H₂O" },
    { name: "Ammonia", formula: "NH₃" },
    { name: "Table Salt", formula: "NaCl" },
    { name: "Vinegar", formula: "CH₃COOH" },
    { name: "Epsom Salt", formula: "MgSO₄" },
    { name: "Hydrogen Peroxide", formula: "H₂O₂" },
    { name: "Bleach", formula: "NaClO" },
    { name: "Lime", formula: "Ca(OH)₂" },
    { name: "Sodium Phosphate", formula: "Na₃PO₄" },
    { name: "Baking Soda", formula: "NaHCO₃" },
    { name: "Washing Soda", formula: "Na₂CO₃" },
    { name: "Bleaching Powder", formula: "Ca(OCl)₂" },
    { name: "Cornstarch", formula: "C₈H₁₁O₄" },

    //Acids
    { name: "Hydrochloric Acid", formula: "HCl" },
    { name: "Sulfuric Acid", formula: "H₂SO₄" },
    { name: "Sulfurous Acid", formula: "H₂SO₃" },
    { name: "Sulphurous Acid", formula: "H₂SO₃" },
    { name: "Sulphuric Acid", formula: "H₂SO₄" },
    { name: "Nitric Acid", formula: "HNO₃" },
    { name: "Phosphoric Acid", formula: "H₃PO₄" },
    { name: "Carbonic Acid", formula: "H₂CO₃" },
    { name: "Citric Acid", formula: "C₆H₈O₇" },
    { name: "Formic Acid", formula: "HCOOH" },
    { name: "Hydrofluoric Acid", formula: "HF" },
    { name: "Hydrobromic Acid", formula: "HBr" },
    { name: "Hydroiodic Acid", formula: "HI" },
    { name: "Oxalic Acid", formula: "C₂H₂O₄" },
    { name: "Tartaric Acid", formula: "C₄H₆O₆" },
    { name: "Lactic Acid", formula: "C₃H₆O₃" },
    { name: "Benzoic Acid", formula: "C₆H₅COOH" },
    { name: "Perchloric Acid", formula: "HClO₄" },
    { name: "Chromic Acid", formula: "H₂CrO₄" },
    { name: "Hydrosulfuric Acid", formula: "H₂S" },
    { name: "Hydrosulphuric Acid", formula: "H₂S" },
    { name: "Boric Acid", formula: "H₃BO₃" },
    { name: "Selenic Acid", formula: "H₂SeO₄" },
    { name: "Acetic Acid", formula: "C₂H₄O₂" },
    { name: "Lactic Acid", formula: "C₃H₆O₃" },
    { name: "Citric Acid", formula: "C₆H₈O₇" },
    { name: "Salicylic Acid", formula: "C₇H₆O₃" },
    { name: "Stearic Acid", formula: "C₁₈H₃₆O₂" },

    //Nitrates
    { name: "Sodium Nitrate", formula: "NaNO₃" },
    { name: "Potassium Nitrate", formula: "KNO₃" },
    { name: "Calcium Nitrate", formula: "Ca(NO₃)₂" },
    { name: "Magnesium Nitrate", formula: "Mg(NO₃)₂" },
    { name: "Ammonium Nitrate", formula: "NH₄NO₃" },
    { name: "Lithium Nitrate", formula: "LiNO₃" },
    { name: "Silver Nitrate", formula: "AgNO₃" },
    { name: "Barium Nitrate", formula: "Ba(NO₃)₂" },
    { name: "Strontium Nitrate", formula: "Sr(NO₃)₂" },
    { name: "Zinc Nitrate", formula: "Zn(NO₃)₂" },
    { name: "Copper(II) Nitrate", formula: "Cu(NO₃)₂" },
    { name: "Copper Nitrate", formula: "Cu(NO₃)₂" },
    { name: "Iron(II) Nitrate", formula: "Fe(NO₃)₂" },
    { name: "Iron(III) Nitrate", formula: "Fe(NO₃)₃" },
    { name: "Lead(II) Nitrate", formula: "Pb(NO₃)₂" },
    { name: "Lead Nitrate", formula: "Pb(NO₃)₂" },
    { name: "Nickel(II) Nitrate", formula: "Ni(NO₃)₂" },
    { name: "Nickel Nitrate", formula: "Ni(NO₃)₂" },
    { name: "Cobalt(II) Nitrate", formula: "Co(NO₃)₂" },
    { name: "Cobalt Nitrate", formula: "Co(NO₃)₂" },
    { name: "Manganese(II) Nitrate", formula: "Mn(NO₃)₂" },
    { name: "Manganese Nitrate", formula: "Mn(NO₃)₂" },
    { name: "Mercury(II) Nitrate", formula: "Hg(NO₃)₂" },
    { name: "Mercury Nitrate", formula: "Hg(NO₃)₂" },
    { name: "Aluminum Nitrate", formula: "Al(NO₃)₃" },
    { name: "Bismuth Nitrate", formula: "Bi(NO₃)₃" },

    //Nitrides
    { name: "Sodium Nitride", formula: "Na₃N" },
    { name: "Potassium Nitride", formula: "K₃N" },
    { name: "Silver Nitride", formula: "Ag₃N" },
    { name: "Magnesium Nitride", formula: "Mg₃N₂" },
    { name: "Calcium Nitride", formula: "Ca₃N₂" },
    { name: "Aluminum Nitride", formula: "AlN" },
    { name: "Silicon Nitride", formula: "Si₃N₄" },
    { name: "Gallium Nitride", formula: "GaN" },
    { name: "Boron Nitride", formula: "BN" },
    { name: "Titanium Nitride", formula: "TiN" },
    { name: "Zirconium Nitride", formula: "ZrN" },
    { name: "Hafnium Nitride", formula: "HfN" },
    { name: "Iron(III) Nitride", formula: "FeN" },
    { name: "Lead(II) Nitride", formula: "Pb₃N₂" },
    { name: "Lead Nitride", formula: "Pb₃N₂" },
    { name: "Copper(I) Nitride", formula: "Cu₃N" },
    { name: "Indium Nitride", formula: "InN" },
    { name: "Mercury(II) Nitride", formula: "Hg₃N₂" },
    { name: "Zinc Nitride", formula: "Zn₃N₂" },
    { name: "Mercury Nitride", formula: "Hg₃N₂" },

    //Sulphates/Sulfates
    { name: "Sodium Sulphate", formula: "Na₂SO₄" },
    { name: "Silver Sulphate", formula: "Ag₂SO₄" },
    { name: "Potassium Sulphate", formula: "K₂SO₄" },
    { name: "Calcium Sulphate", formula: "CaSO₄" },
    { name: "Magnesium Sulphate", formula: "MgSO₄" },
    { name: "Iron(II) Sulphate", formula: "FeSO₄" },
    { name: "Iron(III) Sulphate", formula: "Fe₂(SO₄)₃" },
    { name: "Copper(II) Sulphate", formula: "CuSO₄" },
    { name: "Copper Sulphate", formula: "CuSO₄" },
    { name: "Zinc Sulphate", formula: "ZnSO₄" },
    { name: "Aluminum Sulphate", formula: "Al₂(SO₄)₃" },
    { name: "Ammonium Sulphate", formula: "(NH₄)₂SO₄" },
    { name: "Lead(II) Sulphate", formula: "PbSO₄" },
    { name: "Lead Sulphate", formula: "PbSO₄" },
    { name: "Barium Sulphate", formula: "BaSO₄" },
    { name: "Lithium Sulphate", formula: "Li₂SO₄" },
    { name: "Mercury Sulphate", formula: "HgSO₄" },
    //---
    { name: "Silver Sulfhate", formula: "Ag₂SO₄" },
    { name: "Sodium Sulfate", formula: "Na₂SO₄" },
    { name: "Potassium Sulfate", formula: "K₂SO₄" },
    { name: "Calcium Sulfate", formula: "CaSO₄" },
    { name: "Magnesium Sulfate", formula: "MgSO₄" },
    { name: "Iron(II) Sulfate", formula: "FeSO₄" },
    { name: "Iron(III) Sulfate", formula: "Fe₂(SO₄)₃" },
    { name: "Copper(II) Sulfate", formula: "CuSO₄" },
    { name: "Copper Sulfate", formula: "CuSO₄" },
    { name: "Zinc Sulfate", formula: "ZnSO₄" },
    { name: "Aluminum Sulfate", formula: "Al₂(SO₄)₃" },
    { name: "Ammonium Sulfate", formula: "(NH₄)₂SO₄" },
    { name: "Lead(II) Sulfate", formula: "PbSO₄" },
    { name: "Lead Sulfate", formula: "PbSO₄" },
    { name: "Barium Sulfate", formula: "BaSO₄" },
    { name: "Lithium Sulfate", formula: "Li₂SO₄" },
    { name: "Mercury Sulfate", formula: "HgSO₄" },

    //Sulphides/Sulfides
    { name: "Sodium Sulphide", formula: "Na₂S" },
    { name: "Potassium Sulphide", formula: "K₂S" },
    { name: "Calcium Sulphide", formula: "CaS" },
    { name: "Magnesium Sulphide", formula: "MgS" },
    { name: "Iron(II) Sulphide", formula: "FeS" },
    { name: "Iron(III) Sulphide", formula: "Fe₂S₃" },
    { name: "Copper(I) Sulphide", formula: "Cu₂S" },
    { name: "Copper(II) Sulphide", formula: "CuS" },
    { name: "Zinc Sulphide", formula: "ZnS" },
    { name: "Aluminum Sulphide", formula: "Al₂S₃" },
    { name: "Silver Sulphide", formula: "Ag₂S" },
    { name: "Lead(II) Sulphide", formula: "PbS" },
    { name: "Lead Sulphide", formula: "PbS" },
    { name: "Barium Sulphide", formula: "BaS" },
    { name: "Lithium Sulphide", formula: "Li₂S" },
    { name: "Mercury Sulphide", formula: "HgS" },
    //---
    { name: "Sodium Sulfide", formula: "Na₂S" },
    { name: "Mercury Sulfide", formula: "HgS" },
    { name: "Potassium Sulfide", formula: "K₂S" },
    { name: "Calcium Sulfide", formula: "CaS" },
    { name: "Magnesium Sulfide", formula: "MgS" },
    { name: "Iron(II) Sulfide", formula: "FeS" },
    { name: "Iron(III) Sulfide", formula: "Fe₂S₃" },
    { name: "Copper(I) Sulfide", formula: "Cu₂S" },
    { name: "Copper(II) Sulfide", formula: "CuS" },
    { name: "Zinc Sulfide", formula: "ZnS" },
    { name: "Aluminum Sulfide", formula: "Al₂S₃" },
    { name: "Silver Sulfide", formula: "Ag₂S" },
    { name: "Lead(II) Sulfide", formula: "PbS" },
    { name: "Lead Sulfide", formula: "PbS" },
    { name: "Barium Sulfide", formula: "BaS" },
    { name: "Lithium Sulfide", formula: "Li₂S" },
    { name: "Hydrogen Sulphide", formula: "H₂S" },
    { name: "Hydrogen Sulfide", formula: "H₂S" },

    //Iodides
    { name: "Sodium Iodide", formula: "NaI" },
    { name: "Potassium Iodide", formula: "KI" },
    { name: "Aluminum Iodide", formula: "AlI₃" },
    { name: "Lithium Iodide", formula: "LiI" },
    { name: "Calcium Iodide", formula: "CaI₂" },
    { name: "Magnesium Iodide", formula: "MgI₂" },
    { name: "Hydrogen Iodide", formula: "HI" },
    { name: "Zinc Iodide", formula: "ZnI₂" },
    { name: "Iron(II) Iodide", formula: "FeI₂" },
    { name: "Iron(III) Iodide", formula: "FeI₃" },
    { name: "Copper(I) Iodide", formula: "CuI" },
    { name: "Copper(II) Iodide", formula: "CuI₂" },
    { name: "Barium Iodide", formula: "BaI₂" },
    { name: "Strontium Iodide", formula: "SrI₂" },
    { name: "Nickel(II) Iodide", formula: "NiI₂" },
    { name: "Nickel Iodide", formula: "NiI₂" },
    { name: "Lead(II) Iodide", formula: "PbI₂" },
    { name: "Lead Iodide", formula: "PbI₂" },
    { name: "Silver Iodide", formula: "AgI" },
    { name: "Ammonium Iodide", formula: "NH₄I" },
    { name: "Mercury(I) Iodide", formula: "Hg₂I₂" },
    { name: "Mercury(II) Iodide", formula: "HgI₂" },

    //Acetates
    { name: "Sodium Acetate", formula: "CH₃COONa" },
    { name: "Potassium Acetate", formula: "CH₃COOK" },
    { name: "Calcium Acetate", formula: "C₄H₆CaO₄" },
    { name: "Magnesium Acetate", formula: "C₄H₆MgO₄" },
    { name: "Ammonium Acetate", formula: "CH₃COONH₄" },
    { name: "Lithium Acetate", formula: "CH₃COOLi" },
    { name: "Zinc Acetate", formula: "C₄H₆O₄Zn" },
    { name: "Aluminum Acetate", formula: "C₆H₉AlO₆" },
    { name: "Iron(II) Acetate", formula: "Fe(C₂H₃O₂)₂" },
    { name: "Iron(III) Acetate", formula: "Fe(C₂H₃O₂)₃" },
    { name: "Copper(II) Acetate", formula: "Cu(C₂H₃O₂)₂" },
    { name: "Copper Acetate", formula: "Cu(C₂H₃O₂)₂" },
    { name: "Lead(II) Acetate", formula: "Pb(C₂H₃O₂)₂" },
    { name: "Lead Acetate", formula: "Pb(C₂H₃O₂)₂" },
    { name: "Nickel(II) Acetate", formula: "Ni(C₂H₃O₂)₂" },
    { name: "Nickel Acetate", formula: "Ni(C₂H₃O₂)₂" },
    { name: "Cobalt(II) Acetate", formula: "Co(C₂H₃O₂)₂" },
    { name: "Cobalt Acetate", formula: "Co(C₂H₃O₂)₂" },
    { name: "Manganese(II) Acetate", formula: "Mn(C₂H₃O₂)₂" },
    { name: "Manganese Acetate", formula: "Mn(C₂H₃O₂)₂" },
    { name: "Silver Acetate", formula: "CH₃COOAg" },
    { name: "Mercury(II) Acetate", formula: "Hg(C₂H₃O₂)₂" },
    { name: "Mercury Acetate", formula: "Hg(C₂H₃O₂)₂" },
    { name: "Barium Acetate", formula: "Ba(C₂H₃O₂)₂" },
    { name: "Strontium Acetate", formula: "Sr(C₂H₃O₂)₂" },

    //Chlorides
    { name: "Mercury Chloride", formula: "HgCl₂" },
    { name: "Sodium Chloride", formula: "NaCl" },
    { name: "Potassium Chloride", formula: "KCl" },
    { name: "Calcium Chloride", formula: "CaCl₂" },
    { name: "Magnesium Chloride", formula: "MgCl₂" },
    { name: "Iron(III) Chloride", formula: "FeCl₃" },
    { name: "Iron(II) Chloride", formula: "FeCl₂" },
    { name: "Aluminum Chloride", formula: "AlCl₃" },
    { name: "Copper(II) Chloride", formula: "CuCl₂" },
    { name: "Copper Chloride", formula: "CuCl₂" },
    { name: "Zinc Chloride", formula: "ZnCl₂" },
    { name: "Hydrogen Chloride", formula: "HCl" },
    { name: "Ammonium Chloride", formula: "NH₄Cl" },
    { name: "Silver Chloride", formula: "AgCl" },
    { name: "Lead(II) Chloride", formula: "PbCl₂" },
    { name: "Lead Chloride", formula: "PbCl₂" },
    { name: "Lithium Chloride", formula: "LiCl" },
    { name: "Barium Chloride", formula: "BaCl₂" },

    //Bromides
    { name: "Sodium Bromide", formula: "NaBr" },
    { name: "Mercury Bromide", formula: "HgBr₂" },
    { name: "Potassium Bromide", formula: "KBr" },
    { name: "Calcium Bromide", formula: "CaBr₂" },
    { name: "Magnesium Bromide", formula: "MgBr₂" },
    { name: "Iron(III) Bromide", formula: "FeBr₃" },
    { name: "Iron(II) Bromide", formula: "FeBr₂" },
    { name: "Copper(II) Bromide", formula: "CuBr₂" },
    { name: "Copper Bromide", formula: "CuBr₂" },
    { name: "Zinc Bromide", formula: "ZnBr₂" },
    { name: "Aluminum Bromide", formula: "AlBr₃" },
    { name: "Silver Bromide", formula: "AgBr" },
    { name: "Lithium Bromide", formula: "LiBr" },
    { name: "Lead Bromide", formula: "PbBr₂" },

    //Oxides
    { name: "Sodium Oxide", formula: "Na₂O" },
    { name: "Mercury Oxide", formula: "HgO" },
    { name: "Potassium Oxide", formula: "K₂O" },
    { name: "Calcium Oxide", formula: "CaO" },
    { name: "Magnesium Oxide", formula: "MgO" },
    { name: "Iron(II) Oxide", formula: "FeO" },
    { name: "Iron(III) Oxide", formula: "Fe₂O₃" },
    { name: "Copper(II) Oxide", formula: "CuO" },
    { name: "Copper Oxide", formula: "CuO" },
    { name: "Zinc Oxide", formula: "ZnO" },
    { name: "Aluminum Oxide", formula: "Al₂O₃" },
    { name: "Lead(II) Oxide", formula: "PbO" },
    { name: "Lead Oxide", formula: "PbO" },
    { name: "Silver Oxide", formula: "Ag₂O." },
    { name: "Barium Oxide", formula: "BaO" },
    { name: "Lithium Oxide", formula: "Li₂O" },
    { name: "Carbon Monoxide", formula: "CO" },
    { name: "Carbon Dioxide", formula: "CO₂" },
    { name: "Sulphur Dioxide", formula: "SO₂" },
    { name: "Sulphur Trioxide", formula: "SO₃" },
    { name: "Sulfur Dioxide", formula: "SO₂" },
    { name: "Sulfur Trioxide", formula: "SO₃" },
    { name: "Phosphorus Pentoxide", formula: "P₂O₅" },
    
    //Hydroxides
    { name: "Sodium Hydroxide", formula: "NaOH" },
    { name: "Potassium Hydroxide", formula: "KOH" },
    { name: "Calcium Hydroxide", formula: "Ca(OH)₂" },
    { name: "Magnesium Hydroxide", formula: "Mg(OH)₂" },
    { name: "Iron(II) Hydroxide", formula: "Fe(OH)₂" },
    { name: "Mercury Hydroxide", formula: "Hg(OH)₂" },
    { name: "Iron(III) Hydroxide", formula: "Fe(OH)₃" },
    { name: "Copper(II) Hydroxide", formula: "Cu(OH)₂" },
    { name: "Copper Hydroxide", formula: "Cu(OH)₂" },
    { name: "Aluminum Hydroxide", formula: "Al(OH)₃" },
    { name: "Zinc Hydroxide", formula: "Zn(OH)₂" },
    { name: "Barium Hydroxide", formula: "Ba(OH)₂" },
    { name: "Lead(II) Hydroxide", formula: "Pb(OH)₂" },
    { name: "Lead Hydroxide", formula: "Pb(OH)₂" },
    { name: "Lithium Hydroxide", formula: "LiOH" },
    { name: "Silver Hydroxide", formula: "AgOH" },
    { name: "Ammonium Hydroxide", formula: "NH₄OH" },
    { name: "Strontium Hydroxide", formula: "Sr(OH)₂" },
    { name: "Nickel(II) Hydroxide", formula: "Ni(OH)₂" },
    { name: "Nickel Hydroxide", formula: "Ni(OH)₂" },
    { name: "Cobalt(II) Hydroxide", formula: "Co(OH)₂" },
    { name: "Cobalt Hydroxide", formula: "Co(OH)₂" },

    //Carbonates
    { name: "Sodium Carbonate", formula: "Na₂CO₃" },
    { name: "Mercury Carbonate", formula: "HgCO₃" },
    { name: "Aluminum Carbonate", formula: "Al₂(CO₃)₃" },
    { name: "Calcium Carbonate", formula: "CaCO₃" },
    { name: "Magnesium Carbonate", formula: "MgCO₃" },
    { name: "Potassium Carbonate", formula: "K₂CO₃" },
    { name: "Lithium Carbonate", formula: "Li₂CO₃" },
    { name: "Copper(II) Carbonate", formula: "CuCO₃" },
    { name: "Copper Carbonate", formula: "CuCO₃" },
    { name: "Zinc Carbonate", formula: "ZnCO₃" },
    { name: "Iron(II) Carbonate", formula: "FeCO₃" },
    { name: "Iron Carbonate", formula: "FeCO₃" },
    { name: "Manganese Carbonate", formula: "MnCO₃" },
    { name: "Barium Carbonate", formula: "BaCO₃" },
    { name: "Strontium Carbonate", formula: "SrCO₃" },
    { name: "Lead(II) Carbonate", formula: "PbCO₃" },
    { name: "Lead Carbonate", formula: "PbCO₃" },
    { name: "Nickel(II) Carbonate", formula: "NiCO₃" },
    { name: "Nickel Carbonate", formula: "NiCO₃" },
    { name: "Cobalt(II) Carbonate", formula: "CoCO₃" },
    { name: "Cobalt Carbonate", formula: "CoCO₃" },
    { name: "Ammonium Carbonate", formula: "(NH₄)₂CO₃" },
    { name: "Silver Carbonate", formula: "Ag₂CO₃" },
    { name: "Bismuth Carbonate", formula: "Bi₂(CO₃)₃" },

    //Bicarbonates/Hydrogencarbonates
    { name: "Sodium Bicarbonate", formula: "NaHCO₃" },
    { name: "Mercury Bicarbonate", formula: "Hg(HCO₃)₂" },
    { name: "Aluminum Bicarbonate", formula: "Al(HCO₃)₃" },
    { name: "Potassium Bicarbonate", formula: "KHCO₃" },
    { name: "Calcium Bicarbonate", formula: "Ca(HCO₃)₂" },
    { name: "Magnesium Bicarbonate", formula: "Mg(HCO₃)₂" },
    { name: "Ammonium Bicarbonate", formula: "NH₄HCO₃" },
    { name: "Lithium Bicarbonate", formula: "LiHCO₃" },
    { name: "Iron(II) Bicarbonate", formula: "Fe(HCO₃)₂" },
    { name: "Iron Bicarbonate", formula: "Fe(HCO₃)₂" },
    { name: "Zinc Bicarbonate", formula: "Zn(HCO₃)₂" },
    { name: "Copper(II) Bicarbonate", formula: "Cu(HCO₃)₂" },
    { name: "Copper Bicarbonate", formula: "Cu(HCO₃)₂" },
    { name: "Silver Bicarbonate", formula: "AgHCO₃" },
    { name: "Strontium Bicarbonate", formula: "Sr(HCO₃)₂" },
    { name: "Barium Bicarbonate", formula: "Ba(HCO₃)₂" },
    { name: "Nickel(II) Bicarbonate", formula: "Ni(HCO₃)₂" },
    { name: "Nickel Bicarbonate", formula: "Ni(HCO₃)₂" },
    { name: "Lead Bicarbonate", formula: "Pb(HCO₃)₂" },
    //---
    { name: "Sodium Hydrogen Carbonate", formula: "NaHCO₃" },
    { name: "Silver Hydrogen Carbonate", formula: "AgHCO₃" },
    { name: "Mercury Hydrogen Carbonate", formula: "Hg(HCO₃)₂" },
    { name: "Aluminum Hydrogen Carbonate", formula: "Al(HCO₃)₃" },
    { name: "Potassium Hydrogen Carbonate", formula: "KHCO₃" },
    { name: "Calcium Hydrogen Carbonate", formula: "Ca(HCO₃)₂" },
    { name: "Magnesium Hydrogen Carbonate", formula: "Mg(HCO₃)₂" },
    { name: "Ammonium Hydrogen Carbonate", formula: "NH₄HCO₃" },
    { name: "Lithium Hydrogen Carbonate", formula: "LiHCO₃" },
    { name: "Iron(II) Hydrogen Carbonate", formula: "Fe(HCO₃)₂" },
    { name: "Iron Hydrogen Carbonate", formula: "Fe(HCO₃)₂" },
    { name: "Zinc Hydrogen Carbonate", formula: "Zn(HCO₃)₂" },
    { name: "Copper(II) Hydrogen Carbonate", formula: "Cu(HCO₃)₂" },
    { name: "Copper Hydrogen Carbonate", formula: "Cu(HCO₃)₂" },
    { name: "Strontium Hydrogen Carbonate", formula: "Sr(HCO₃)₂" },
    { name: "Barium Hydrogen Carbonate", formula: "Ba(HCO₃)₂" },
    { name: "Nickel(II) Hydrogen Carbonate", formula: "Ni(HCO₃)₂" },
    { name: "Nickel Hydrogen Carbonate", formula: "Ni(HCO₃)₂" },
    { name: "Lead Hydrogen Carbonate", formula: "Pb(HCO₃)₂" },
    //---
    { name: "Sodium Hydrogencarbonate", formula: "NaHCO₃" },
    { name: "Aluminum Hydrogen Carbonate", formula: "Al(HCO₃)₃" },
    { name: "Potassium Hydrogencarbonate", formula: "KHCO₃" },
    { name: "Calcium Hydrogencarbonate", formula: "Ca(HCO₃)₂" },
    { name: "Magnesium Hydrogencarbonate", formula: "Mg(HCO₃)₂" },
    { name: "Ammonium Hydrogencarbonate", formula: "NH₄HCO₃" },
    { name: "Silver Hydrogencarbonate", formula: "AgHCO₃" },
    { name: "Lithium Hydrogencarbonate", formula: "LiHCO₃" },
    { name: "Iron Hydrogencarbonate", formula: "Fe(HCO₃)₂" },
    { name: "Iron(II) Hydrogencarbonate", formula: "Fe(HCO₃)₂" },
    { name: "Zinc Hydrogencarbonate", formula: "Zn(HCO₃)₂" },
    { name: "Mercury Hydrogencarbonate", formula: "Hg(HCO₃)₂" },
    { name: "Copper Hydrogencarbonate", formula: "Cu(HCO₃)₂" },
    { name: "Copper(II) Hydrogencarbonate", formula: "Cu(HCO₃)₂" },
    { name: "Lead Hydrogencarbonate", formula: "Pb(HCO₃)₂" },
    { name: "Strontium Hydrogencarbonate", formula: "Sr(HCO₃)₂" },
    { name: "Barium Hydrogencarbonate", formula: "Ba(HCO₃)₂" },
    { name: "Nickel(II) Hydrogencarbonate", formula: "Ni(HCO₃)₂" },
    { name: "Nickel Hydrogencarbonate", formula: "Ni(HCO₃)₂" },

    //Metals
    { name: "Sodium", formula: "Na" },
    { name: "Potassium", formula: "K" },
    { name: "Calcium", formula: "Ca" },
    { name: "Magnesium", formula: "Mg" },
    { name: "Iron", formula: "Fe" },
    { name: "Copper", formula: "Cu" },
    { name: "Zinc", formula: "Zn" },
    { name: "Aluminum", formula: "Al" },
    { name: "Silver", formula: "Ag" },
    { name: "Gold", formula: "Au" },
    { name: "Lead", formula: "Pb" },
    { name: "Nickel", formula: "Ni" },
    { name: "Platinum", formula: "Pt" },
    { name: "Chromium", formula: "Cr" },
    { name: "Tin", formula: "Sn" },
    { name: "Barium", formula: "Ba" },
    { name: "Strontium", formula: "Sr" },
    { name: "Lithium", formula: "Li" },
    { name: "Titanium", formula: "Ti" },
    { name: "Manganese", formula: "Mn" },
    { name: "Mercury", formula: "Hg" },

    //Non-Metals
    { name: "Hydrogen", formula: "H₂" },
    { name: "Helium", formula: "He" },
    { name: "Carbon", formula: "C" },
    { name: "Nitrogen", formula: "N₂" },
    { name: "Oxygen", formula: "O₂" },
    { name: "Fluorine", formula: "F" },
    { name: "Neon", formula: "Ne" },
    { name: "Phosphorus", formula: "P" },
    { name: "Sulphur", formula: "S" },
    { name: "Sulfur", formula: "S" },
    { name: "Chlorine", formula: "Cl₂" },
    { name: "Argon", formula: "Ar" },
    { name: "Bromine", formula: "Br" },
    { name: "Iodine", formula: "I" },
    { name: "Xenon", formula: "Xe" },
    { name: "Radon", formula: "Rn" },

    //Metalloids
    { name: "Boron", symbol: "B" },
    { name: "Silicon", symbol: "Si" },
    { name: "Germanium", symbol: "Ge" },
    { name: "Arsenic", symbol: "As" },
    { name: "Antimony", symbol: "Sb" },
    { name: "Tellurium", symbol: "Te" },
    { name: "Polonium", symbol: "Po" },
    { name: "Selenium", symbol: "Se" },

    //Carbon Compounds
    { name: "Methane", formula: "CH₄" },
    { name: "Ethane", formula: "C₂H₆" },
    { name: "Propane", formula: "C₃H₈" },
    { name: "Butane", formula: "C₄H₁₀" },
    { name: "Pentane", formula: "C₅H₁₂" },
    { name: "Hexane", formula: "C₆H₁₄" },
    { name: "Heptane", formula: "C₇H₁₆" },
    { name: "Octane", formula: "C₈H₁₈" },
    { name: "Nonane", formula: "C₉H₂₀" },
    { name: "Decane", formula: "C₁₀H₂₂" },
    { name: "Benzene", formula: "C₆H₆" },
    { name: "Toluene", formula: "C₇H₈" },
    { name: "Xylene", formula: "C₈H₁₀" },
    { name: "Ethylene", formula: "C₂H₄" },
    { name: "Ethene", formula: "C₂H₄" },
    { name: "Acetylene", formula: "C₂H₂" },
    { name: "Ethyne", formula: "C₂H₂" },
    { name: "Formaldehyde", formula: "CH₂O" },
    { name: "Urea", formula: "CH₄N₂O" },
    { name: "Fructose", formula: "C₆H₁₂O₆" },
    { name: "Sucrose", formula: "C₁₂H₂₂O₁₁" },
    { name: "Starch", formula: "(C₆H₁₀O₅)ₙ" },
    { name: "Cellulose", formula: "(C₆H₁₀O₅)ₙ" },
    { name: "Cholesterol", formula: "C₂₇H₄₆O" },
    { name: "Aspirin", formula: "C₉H₈O₄" },
    { name: "Methanol", formula: "CH₃OH" },
    { name: "Ethanol", formula: "C₂H₅OH" },
    { name: "Isopropanol", formula: "C₃H₈O" },
    { name: "Acetone", formula: "C₃H₆O" },
    { name: "Polyethylene", formula: "(C₂H₄)ₙ" },
    { name: "Polystyrene", formula: "(C₈H₈)ₙ" },
    { name: "Polytetrafluoroethylene", formula: "(C₂F₄)ₙ" },
    { name: "Teflon", formula: "(C₂F₄)ₙ" },
    { name: "Benzaldehyde", formula: "C₇H₆O" },

    //Transitions 
    { name: "Added to", formula: "+" },
    { name: "Reacts with", formula: "+" },
    { name: ",", formula: " +" },
    { name: "And", formula: "+" },
    { name: "Reacts to give", formula: "→" },
    { name: "To give", formula: "→" },
    { name: "Forms", formula: "→" },
    { name: "Gives", formula: "→" },
    { name: "Combine and forms", formula: "→" },
    { name: "Combines to form", formula: "→" },
    { name: "React and give", formula: "→" },
    { name: "React to give", formula: "→" },
    { name: "React to form", formula: "→" },
    { name: "Combines and forms", formula: "→" },
    { name: "And forms", formula: "→" },
    { name: "And", formula: "→" },
    { name: "To form", formula: "→" },
    { name: "To become", formula: "→" },
    { name: "Becomes", formula: "→" },
    { name: "Become", formula: "→" },
    { name: "React", formula: "→" },
    { name: "Produces", formula: "→" },
    { name: "Yields", formula: "→" },
    { name: "Results in", formula: "→" },
    { name: "Is formed", formula: "→" },
    { name: "Forms from", formula: "→" },
    { name: "Produces from", formula: "→" },
    { name: "Solid", formula: "" },
    { name: "Aqueous", formula: "" },
    { name: "Liquid", formula: "" },
    { name: "Gas", formula: "↑" },
    { name: "Gaseous", formula: "" },
    { name: "Solution", formula: "" },
    { name: ".", formula: "" }
];  
var input = null;
var result = "";

function translateStatement(){
    document.getElementById("output").innerText= "";
    document.getElementById("output").classList.add("loader");
    setTimeout(function(){
        result = "";
        tester = 0;
        input = document.getElementById("input").value.toLowerCase();
        resCheck = input;
        elementsOnly = transitionRay.slice(0, 202);
        for (i=0; i<transitionRay.length; i++){
            chemicalName = transitionRay[i].name.toLowerCase();
            chemicalFormula = transitionRay[i].formula;
            resCheck = resCheck.replace(chemicalName, chemicalFormula);
            if(resCheck!=input){result=resCheck;};
        }
        for (i=0; i<elementsOnly.length; i++){
            chemicalName = elementsOnly[i].name.toLowerCase();
            chemicalFormula = elementsOnly[i].formula;
            reg = /"+"/g;
            trim = result.slice(0, result.search("→")).replace(reg, "");
            if(trim.search(chemicalFormula) < 0){
                tester++;
            }
        }
        result=result.trim();
        document.getElementById("output").classList.remove("loader");
        if(result.search("→")==(result.length)-1){document.getElementById("output").innerText = "Error: No product found!";}
        else if(result.search("→")<0){document.getElementById("output").innerText = "Error: Invalid statement!";}
        else if(result.search("→")>0){document.getElementById("output").innerText = result;}
        if(result.search("→")==0){document.getElementById("output").innerText = "Error: No reactant found!";}
    }, Math.floor(Math.random()*100)*10);
}

function randomEquation(){
    statements = [
        "Hydrogen reacts with oxygen to give water.",
        "Sodium reacts with chlorine to give sodium chloride.",
        "Carbon reacts with oxygen to give carbon dioxide.",
        "Iron reacts with oxygen to give iron(iii) oxide.",
        "Magnesium reacts with hydrochloric acid to give magnesium chloride and hydrogen gas.",
        "Zinc reacts with sulfuric acid to give zinc sulfate and hydrogen gas.",
        "Calcium reacts with water to give calcium hydroxide.",
        "Aluminum reacts with oxygen to give aluminum oxide.",
        "Methane reacts with oxygen to give carbon dioxide and water.",
        "Potassium reacts with water to give potassium hydroxide.",
        "Sodium bicarbonate reacts with acetic acid to give carbon dioxide and water.",
        "Copper reacts with sulfur to give copper(i) sulfide.",
        "Hydrogen reacts with nitrogen to give ammonia.",
        "Silver nitrate reacts with sodium chloride to give silver chloride and sodium nitrate.",
        "Lead reacts with sulfur to give lead sulfide.",
        "Ethanol reacts with oxygen to give carbon dioxide and water.",
        "Calcium carbonate reacts with hydrochloric acid to give calcium chloride, hydrogen and carbon dioxide.",
        "Iron reacts with sulfuric acid to give iron(ii) sulfate and hydrogen gas.",
        "Phosphorus reacts with oxygen to give phosphorus pentoxide.",
        "Ammonia reacts with hydrogen chloride to give ammonium chloride.",
        "Sodium reacts with water to give sodium hydroxide and hydrogen gas.",
        "Sulfur dioxide reacts with water to give sulfurous acid.",
        "Potassium nitrate reacts with sulfur to give potassium sulfate and nitrogen.",
        "Magnesium reacts with nitrogen to give magnesium nitride."
    ];
    coin = Math.floor(Math.random() * 2)
    if(coin==0){
        integer = Math.floor(Math.random() * statements.length);
    } else if(coin==1){
        integer = Math.floor(Math.random() * (statements.length-2)) + 2;
    }
    document.getElementById("input").value = statements[integer];
    translateStatement();
}